baseurl = "https://ajonp-lesson-4-hugo-ionic.firebaseapp.com"

# adsense = "<your_name>"
# googleAnalytics = "<your_name>"

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.algolia]
vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
params = ["categories", "tags"]

[outputs]
home = ["HTML", "RSS", "Algolia"]